import type { GraphEdge, GraphNode, Source } from './types'

export const sources: Source[] = [
  {
    id: 'osborn',
    short: 'Osborn · 2017',
    title: 'Everything in its Right Place: Analyzing Radiohead',
    author: 'Brad Osborn',
    year: 2017,
    publisher: 'Oxford University Press',
    url: 'https://academic.oup.com/book/8275',
    note: 'Academic core. Formal design, rhythm and meter, timbre, harmony and voice-leading across Radiohead’s mature catalogue.',
    tier: 'academic',
  },
  {
    id: 'letts',
    short: 'Letts · 2010',
    title: 'Radiohead and the Resistant Concept Album: How to Disappear Completely',
    author: 'Marianne Tatom Letts',
    year: 2010,
    publisher: 'Indiana University Press',
    url: 'https://iupress.org/9780253222725/radiohead-and-the-resistant-concept-album/',
    note: 'Academic analysis of Kid A and Amnesiac as a departure from the guitar-led base, with attention to musical structure, alienation and anti-capitalist themes.',
    tier: 'academic',
  },
  {
    id: 'griffiths',
    short: 'Griffiths · 2004',
    title: "Radiohead's OK Computer",
    author: 'Dai Griffiths',
    year: 2004,
    publisher: '33⅓ / Bloomsbury',
    url: 'https://www.bloomsbury.com/uk/radioheads-ok-computer-9780826416636/',
    note: 'Close musical reading of OK Computer and its songs, used here for the album’s internal structure and thematic nodes.',
    tier: 'academic',
  },
  {
    id: 'guardian-2009',
    short: 'The Guardian · 2009',
    title: 'Radiohead: band of the decade',
    author: 'Gareth Grundy',
    year: 2009,
    publisher: 'The Observer / The Guardian',
    url: 'https://www.theguardian.com/music/2009/nov/29/radiohead-interview',
    note: 'Primary interview material. The band describes the transition from guitars to computers; Autechre and Boards of Canada are named among Thom Yorke’s inspirations.',
    tier: 'primary',
  },
  {
    id: 'guardian-2000',
    short: 'The Observer · 2000',
    title: 'Sound and fury',
    author: 'Andrew Smith',
    year: 2000,
    publisher: 'The Observer / The Guardian',
    url: 'https://www.theguardian.com/theobserver/2000/oct/01/life1.lifemagazine',
    note: 'Contemporary primary source on the Kid A rupture. Yorke describes losing interest in guitar music and shifting emphasis toward rhythm; the article identifies Aphex Twin and Autechre as electronic reference points.',
    tier: 'primary',
  },
  {
    id: 'pitchfork-2008',
    short: 'Pitchfork · 2008',
    title: 'Radiohead — Colin Greenwood interview',
    author: 'Ryan Dombal',
    year: 2008,
    publisher: 'Pitchfork',
    url: 'https://pitchfork.com/features/interview/7489-radiohead/',
    note: 'Primary interview about In Rainbows: Nigel Godrich, the fast re-recording of 15 Step and Weird Fishes/Arpeggi, and the band’s pursuit of immediacy and emotional pull.',
    tier: 'primary',
  },
  {
    id: 'pitchfork-2016',
    short: 'Pitchfork / NPR · 2016',
    title: 'Jonny Greenwood breaks down A Moon Shaped Pool tracks',
    author: 'Jazz Monroe, reporting an NPR interview with Jonny Greenwood',
    year: 2016,
    publisher: 'Pitchfork / NPR',
    url: 'https://pitchfork.com/news/67299-listen-to-jonny-greenwood-break-down-radiohead-a-moon-shaped-pool-tracks/',
    note: 'Primary production source for Burn the Witch, Daydreaming and Glass Eyes: strings-first arranging, plectrum-strummed strings, and Max/MSP in the recording process.',
    tier: 'primary',
  },
  {
    id: 'rpl',
    short: 'Radiohead · official',
    title: 'The Radiohead Public Library',
    year: 2020,
    publisher: 'Radiohead',
    url: 'https://www.radiohead.com/library/',
    note: 'Official archive for releases, artwork, video and era-specific materials. Used as the project’s visual and documentary reference layer.',
    tier: 'official',
  },
  {
    id: 'xl',
    short: 'XL · official',
    title: 'Radiohead discography',
    year: 2026,
    publisher: 'XL Recordings',
    url: 'https://shop.xlrecordings.com/artist/94856-radiohead?lang=en_GB',
    note: 'Official discographic metadata and release chronology.',
    tier: 'official',
  },
]

export const nodes: GraphNode[] = [
  { id: 'pablo', label: 'Pablo Honey', kind: 'album', year: 1993, lane: 2, summary: 'The early baseline: one of the two comparatively more predictable albums that Osborn contrasts with Radiohead’s mature period from OK Computer onward.', sourceIds: ['xl', 'osborn'] },
  { id: 'bends', label: 'The Bends', kind: 'album', year: 1995, lane: 2, summary: 'The guitar-led Radiohead that becomes the expectation their later work repeatedly bends and dismantles.', sourceIds: ['xl', 'osborn'] },
  { id: 'okc', label: 'OK Computer', kind: 'album', year: 1997, lane: 2, featured: true, eyebrow: 'FOCUS I', summary: 'A key threshold: still recognisably a rock album, but already organised around formal, timbral and harmonic surprise. Griffiths treats it as a tightly realised album-scale work.', sourceIds: ['xl', 'griffiths', 'osborn'] },
  { id: 'kida', label: 'Kid A', kind: 'album', year: 2000, lane: 2, featured: true, eyebrow: 'FOCUS II', summary: 'The rupture. Letts frames Kid A as a major departure from the group’s guitar-driven base; contemporary interviews describe a shift toward computers, textures, editing and electronic listening.', sourceIds: ['xl', 'letts', 'guardian-2000', 'guardian-2009'] },
  { id: 'amnesiac', label: 'Amnesiac', kind: 'album', year: 2001, lane: 2, summary: 'A companion body of work to Kid A, read by Letts as part of the same resistant-concept-album problem but with a different internal character.', sourceIds: ['xl', 'letts'] },
  { id: 'httt', label: 'Hail to the Thief', kind: 'album', year: 2003, lane: 2, summary: 'A restless recombination of the band’s electronic and rock languages after the Kid A / Amnesiac break.', sourceIds: ['xl', 'osborn'] },
  { id: 'rainbows', label: 'In Rainbows', kind: 'album', year: 2007, lane: 2, featured: true, eyebrow: 'FOCUS III', summary: 'A record whose finished character is repeatedly described by the band in terms of emotional pull, direct playing and the release from over-analysis.', sourceIds: ['xl', 'pitchfork-2008', 'osborn'] },
  { id: 'tkol', label: 'The King of Limbs', kind: 'album', year: 2011, lane: 2, summary: 'The endpoint of Osborn’s 1997–2011 analytical span: a mature-period work where repeated rhythmic and timbral strategies remain central.', sourceIds: ['xl', 'osborn'] },
  { id: 'amsp', label: 'A Moon Shaped Pool', kind: 'album', year: 2016, lane: 2, featured: true, eyebrow: 'FOCUS IV', summary: 'A late-period synthesis where orchestration can become the starting structure rather than decorative finish; Greenwood describes the band as arrangers around Yorke’s songs.', sourceIds: ['xl', 'pitchfork-2016'] },

  { id: 'paranoid', label: 'Paranoid Android', kind: 'track', year: 1997, lane: 1, offset: -0.25, summary: 'A conspicuously sectional song inside OK Computer, useful for reading the album through form rather than genre labels alone.', sourceIds: ['griffiths', 'osborn', 'rpl'] },
  { id: 'fitter', label: 'Fitter Happier', kind: 'track', year: 1997, lane: 3, offset: 0.25, summary: 'A compact bridge between OK Computer’s technological imagery, voice treatment and album-scale thematic logic.', sourceIds: ['griffiths', 'rpl'] },
  { id: 'eirp', label: 'Everything in Its Right Place', kind: 'track', year: 2000, lane: 1, offset: -0.4, summary: 'An emblem of the Kid A turn: keyboard-centred material shaped through studio process rather than a conventional three-guitar arrangement.', sourceIds: ['letts', 'guardian-2000', 'rpl'] },
  { id: 'idioteque', label: 'Idioteque', kind: 'track', year: 2000, lane: 3, offset: -0.1, summary: 'A high-salience rhythmic and timbral node inside Kid A, representative of the band’s mature strategy of setting up expectations and then disrupting them.', sourceIds: ['osborn', 'letts', 'rpl'] },
  { id: 'htdc', label: 'How to Disappear Completely', kind: 'track', year: 2000, lane: 4, offset: 0.35, summary: 'A useful counterweight inside Kid A: acoustic and orchestral colour can coexist with the album’s broader break from the established guitar-band model.', sourceIds: ['letts', 'rpl'] },
  { id: 'pyramid', label: 'Pyramid Song', kind: 'track', year: 2001, lane: 1, offset: 0.1, summary: 'Osborn devotes an entire analytical chapter to the track, making it a natural anchor for the graph’s rhythm/harmony layer.', sourceIds: ['osborn', 'rpl'] },
  { id: 'two-plus-two', label: '2 + 2 = 5', kind: 'track', year: 2003, lane: 1, summary: 'Osborn uses the song as an analytical coda in his chapter on form: a compact case for Radiohead’s manipulation of formal expectation.', sourceIds: ['osborn', 'rpl'] },
  { id: '15step', label: '15 Step', kind: 'track', year: 2007, lane: 1, offset: -0.35, summary: 'Colin Greenwood identifies the quick Oxford re-recording of 15 Step and Weird Fishes/Arpeggi as a turning point in the In Rainbows sessions.', sourceIds: ['pitchfork-2008', 'osborn', 'rpl'] },
  { id: 'weirdfishes', label: 'Weird Fishes / Arpeggi', kind: 'track', year: 2007, lane: 3, summary: 'A song repeatedly reworked before the band captured a version with less self-conscious playing; a strong node for process and immediacy.', sourceIds: ['pitchfork-2008', 'rpl'] },
  { id: 'housecards', label: 'House of Cards', kind: 'track', year: 2007, lane: 4, offset: 0.4, summary: 'Colin Greenwood recalls discarded versions and a later rhythmic reworking, reinforcing In Rainbows as a story of reduction, feel and performance decisions.', sourceIds: ['pitchfork-2008', 'rpl'] },
  { id: 'faustarp', label: 'Faust Arp', kind: 'track', year: 2007, lane: 1, offset: 0.38, summary: 'Osborn uses Faust Arp as the analytical coda to his harmony chapter, exposing the album through voice-leading and harmonic organisation.', sourceIds: ['osborn', 'rpl'] },
  { id: 'bloom', label: 'Bloom', kind: 'track', year: 2011, lane: 1, summary: 'A useful late node for Radiohead’s mature rhythmic vocabulary: repetition and rhythmic organisation remain central rather than ornamental.', sourceIds: ['osborn', 'rpl'] },
  { id: 'burnwitch', label: 'Burn the Witch', kind: 'track', year: 2016, lane: 1, offset: -0.32, summary: 'Greenwood says the arrangement began with strings unusually early; violinists create the rhythm by strumming with guitar plectrums.', sourceIds: ['pitchfork-2016', 'rpl'] },
  { id: 'daydreaming', label: 'Daydreaming', kind: 'track', year: 2016, lane: 3, summary: 'A case for arrangement as problem-solving: Greenwood describes the band searching for a way into Yorke’s material rather than merely adding parts.', sourceIds: ['pitchfork-2016', 'rpl'] },
  { id: 'glasseyes', label: 'Glass Eyes', kind: 'track', year: 2016, lane: 4, offset: 0.32, summary: 'Greenwood describes Glass Eyes as essentially strings and Thom, recorded with software he built in Max/MSP.', sourceIds: ['pitchfork-2016', 'rpl'] },

  { id: 'formal', label: 'formal subversion', kind: 'method', year: 1998.5, lane: 0, summary: 'Osborn argues that Radiohead’s mature music repeatedly establishes expectations inherited from rock and then violates them through distinctive formal types.', sourceIds: ['osborn'] },
  { id: 'rhythm', label: 'metric disruption', kind: 'method', year: 2004.6, lane: 0, summary: 'Odd-cardinality meter, changing meter, maximally even rhythms and polytempo are recurring ways Radiohead destabilises the rock backbeat.', sourceIds: ['osborn'] },
  { id: 'timbre', label: 'timbre as structure', kind: 'method', year: 2000.8, lane: 0, summary: 'In Osborn’s framework, timbre is one of the core parameters through which Radiohead creates expectation and surprise, not merely surface colour.', sourceIds: ['osborn'] },
  { id: 'harmony', label: 'harmonic ambiguity', kind: 'method', year: 2006.2, lane: 0, summary: 'Osborn identifies recurring strategies such as absent tonic, double-tonic complexes, sectional centricity and harmonic underdetermination.', sourceIds: ['osborn'] },
  { id: 'editing', label: 'editing / computer logic', kind: 'method', year: 1999.4, lane: 5, summary: 'Contemporary Kid A interviews describe a move away from simply playing songs together toward collecting sounds, editing and making material coherent after the fact.', sourceIds: ['guardian-2000', 'guardian-2009'] },
  { id: 'immediacy', label: 'live immediacy', kind: 'method', year: 2008.2, lane: 5, summary: 'Colin Greenwood contrasts crippling self-conscious analysis with moments of fast recording, emotional pull and a more immediate group performance.', sourceIds: ['pitchfork-2008'] },
  { id: 'strings', label: 'strings-first arranging', kind: 'method', year: 2015.4, lane: 5, summary: 'On Burn the Witch, strings were placed at the beginning of the arrangement process rather than added later as decoration.', sourceIds: ['pitchfork-2016'] },
  { id: 'maxmsp', label: 'Max/MSP process', kind: 'method', year: 2015.8, lane: 5, summary: 'Greenwood describes using self-made Max/MSP software during the recording of Glass Eyes.', sourceIds: ['pitchfork-2016'] },

  { id: 'alienation', label: 'alienation', kind: 'theme', year: 1999.1, lane: 6, summary: 'Letts treats alienation as a central interpretive theme in Kid A / Amnesiac and connects it to the albums’ resistance to stable conceptual identity.', sourceIds: ['letts'] },
  { id: 'anticapital', label: 'anti-capitalism', kind: 'theme', year: 2001.9, lane: 6, summary: 'Letts explicitly situates anti-capitalist concerns inside her reading of the Kid A / Amnesiac pair and Radiohead’s ambivalence toward commodity culture.', sourceIds: ['letts'] },

  { id: 'penderecki', label: 'Krzysztof Penderecki', kind: 'influence', year: 1997.5, lane: 7, summary: 'Jonny Greenwood identified Penderecki as an influence on his string writing around OK Computer and Kid A.', sourceIds: ['guardian-2000'] },
  { id: 'messiaen', label: 'Olivier Messiaen', kind: 'influence', year: 1998.1, lane: 7, summary: 'Jonny Greenwood identified Messiaen alongside Penderecki when discussing influences on his string arrangements for OK Computer and Kid A.', sourceIds: ['guardian-2000'] },
  { id: 'autechre', label: 'Autechre', kind: 'influence', year: 1999, lane: 7, summary: 'Named by the band as part of Yorke’s electronic listening around the post-OK Computer transition.', sourceIds: ['guardian-2009', 'guardian-2000'] },
  { id: 'boards', label: 'Boards of Canada', kind: 'influence', year: 1999.7, lane: 7, summary: 'Named in the band’s retrospective account as one of the electronic reference points around the move from guitars toward computers.', sourceIds: ['guardian-2009'] },
  { id: 'aphex', label: 'Aphex Twin', kind: 'influence', year: 2000.35, lane: 7, summary: 'Contemporary Kid A coverage and archived interview material link Yorke’s engagement with the Warp catalogue, including Aphex Twin, to the search for new sounds and structures.', sourceIds: ['guardian-2000'] },
]

export const edges: GraphEdge[] = [
  { id: 'pablo-bends', from: 'pablo', to: 'bends', type: 'evolves', label: 'builds the guitar baseline', sourceIds: ['osborn', 'xl'], note: 'Osborn groups the first two albums as the comparatively more predictable baseline against which the mature-period disruptions become legible.' },
  { id: 'bends-okc', from: 'bends', to: 'okc', type: 'evolves', label: 'expands the rock model', sourceIds: ['osborn', 'griffiths'], note: 'The Bends establishes a comparatively more predictable baseline; Osborn’s mature analytical period begins with OK Computer.' },
  { id: 'okc-kida', from: 'okc', to: 'kida', type: 'evolves', label: 'rupture / reinvention', sourceIds: ['letts', 'guardian-2009', 'guardian-2000'], note: 'The move is explicitly framed as a departure from the established guitar-led base toward computers, editing, textures and new listening habits.' },
  { id: 'kida-amnesiac', from: 'kida', to: 'amnesiac', type: 'echoes', label: 'companion problem', sourceIds: ['letts'], note: 'Letts reads Kid A and Amnesiac together as paired but distinct responses to the concept-album tradition.' },
  { id: 'amnesiac-httt', from: 'amnesiac', to: 'httt', type: 'evolves', label: 'recombines languages', sourceIds: ['osborn'], note: 'The mature catalogue repeatedly reuses a limited set of formal, rhythmic, timbral and harmonic disruption strategies in new combinations.' },
  { id: 'httt-rainbows', from: 'httt', to: 'rainbows', type: 'evolves', label: 'toward immediacy', sourceIds: ['pitchfork-2008'], note: 'Colin Greenwood describes the In Rainbows sessions as turning when the band captured strong versions quickly and stopped overthinking every move.' },
  { id: 'rainbows-tkol', from: 'rainbows', to: 'tkol', type: 'echoes', label: 'mature vocabulary', sourceIds: ['osborn'], note: 'Both sit inside Osborn’s 1997–2011 mature period, analysed through recurring expectation/surprise strategies.' },
  { id: 'tkol-amsp', from: 'tkol', to: 'amsp', type: 'evolves', label: 'arrangement becomes foreground', sourceIds: ['pitchfork-2016'], note: 'Greenwood’s account of A Moon Shaped Pool emphasises arrangement decisions, orchestration and song-specific production tools.' },

  { id: 'okc-paranoid', from: 'okc', to: 'paranoid', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'okc-fitter', from: 'okc', to: 'fitter', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'kida-eirp', from: 'kida', to: 'eirp', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'kida-idioteque', from: 'kida', to: 'idioteque', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'kida-htdc', from: 'kida', to: 'htdc', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'amnesiac-pyramid', from: 'amnesiac', to: 'pyramid', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'httt-225', from: 'httt', to: 'two-plus-two', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'rainbows-15', from: 'rainbows', to: '15step', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'rainbows-weird', from: 'rainbows', to: 'weirdfishes', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'rainbows-house', from: 'rainbows', to: 'housecards', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'rainbows-faust', from: 'rainbows', to: 'faustarp', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'tkol-bloom', from: 'tkol', to: 'bloom', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'amsp-burn', from: 'amsp', to: 'burnwitch', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'amsp-day', from: 'amsp', to: 'daydreaming', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },
  { id: 'amsp-glass', from: 'amsp', to: 'glasseyes', type: 'contains', label: 'track', sourceIds: ['xl', 'rpl'], note: 'Album-track relation.' },

  { id: 'paranoid-formal', from: 'paranoid', to: 'formal', type: 'uses', label: 'sectional form', sourceIds: ['griffiths', 'osborn'], note: 'The track is useful for understanding Radiohead’s mature preference for conspicuous formal segmentation and expectation management.' },
  { id: '225-formal', from: 'two-plus-two', to: 'formal', type: 'uses', label: 'formal expectation', sourceIds: ['osborn'], note: 'Osborn uses 2 + 2 = 5 as the analytical coda in the book’s chapter on form.' },
  { id: 'idioteque-rhythm', from: 'idioteque', to: 'rhythm', type: 'uses', label: 'rhythmic salience', sourceIds: ['osborn'], note: 'Placed under Osborn’s rhythm/meter framework: mature Radiohead repeatedly complicates the inherited rock backbeat.' },
  { id: '15-rhythm', from: '15step', to: 'rhythm', type: 'uses', label: 'metric disruption', sourceIds: ['osborn'], note: 'A strong late-period node for the rhythm/meter lens in Osborn’s 1997–2011 catalogue.' },
  { id: 'pyramid-harmony', from: 'pyramid', to: 'harmony', type: 'uses', label: 'analytical anchor', sourceIds: ['osborn'], note: 'Pyramid Song receives a full dedicated chapter after Osborn’s sections on rhythm, timbre and harmony.' },
  { id: 'faust-harmony', from: 'faustarp', to: 'harmony', type: 'uses', label: 'voice-leading case', sourceIds: ['osborn'], note: 'Faust Arp is the analytical coda of Osborn’s harmony and voice-leading chapter.' },
  { id: 'eirp-timbre', from: 'eirp', to: 'timbre', type: 'uses', label: 'studio-shaped timbre', sourceIds: ['letts', 'guardian-2000'], note: 'The Kid A process is described in terms of sounds, textures and editing rather than simply reproducing a band arrangement.' },
  { id: 'kida-editing', from: 'kida', to: 'editing', type: 'uses', label: 'production logic', sourceIds: ['guardian-2000', 'guardian-2009'], note: 'The transition is explicitly described as movement from guitars toward computers and editing-oriented work.' },
  { id: 'editing-timbre', from: 'editing', to: 'timbre', type: 'echoes', label: 'sound becomes compositional', sourceIds: ['osborn', 'guardian-2000'], note: 'Production method and timbre become intertwined analytical layers rather than separate ornament.' },
  { id: 'rainbows-immediacy', from: 'rainbows', to: 'immediacy', type: 'uses', label: 'session turning point', sourceIds: ['pitchfork-2008'], note: 'Colin Greenwood contrasts over-analysis with the strong, quickly captured Oxford versions that helped unlock the record.' },
  { id: '15-immediacy', from: '15step', to: 'immediacy', type: 'uses', label: 'fast re-recording', sourceIds: ['pitchfork-2008'], note: '15 Step was re-recorded in Oxford during the session Colin Greenwood identifies as a turning point.' },
  { id: 'weird-immediacy', from: 'weirdfishes', to: 'immediacy', type: 'uses', label: 'less self-conscious playing', sourceIds: ['pitchfork-2008'], note: 'The successful version arrived after many attempts when the band played with less conscious control.' },
  { id: 'house-immediacy', from: 'housecards', to: 'immediacy', type: 'uses', label: 'rhythmic reworking', sourceIds: ['pitchfork-2008'], note: 'Colin describes discarded versions before Phil Selway and Thom Yorke arrived at the eventual rhythm.' },
  { id: 'amsp-strings', from: 'amsp', to: 'strings', type: 'uses', label: 'arrangement-first logic', sourceIds: ['pitchfork-2016'], note: 'Greenwood characterises the album’s work in terms of arrangement choices and specifically highlights starting Burn the Witch with strings.' },
  { id: 'burn-strings', from: 'burnwitch', to: 'strings', type: 'uses', label: 'plectrum-strummed strings', sourceIds: ['pitchfork-2016'], note: 'The strings carry the rhythmic mechanism, with violinists strumming using guitar picks.' },
  { id: 'glass-max', from: 'glasseyes', to: 'maxmsp', type: 'uses', label: 'custom software', sourceIds: ['pitchfork-2016'], note: 'Greenwood says the recording used software he had made in Max/MSP.' },
  { id: 'day-strings', from: 'daydreaming', to: 'strings', type: 'echoes', label: 'arrangement problem-solving', sourceIds: ['pitchfork-2016'], note: 'Greenwood frames the band’s role around finding an arrangement that does not diminish Yorke’s song.' },

  { id: 'kida-alienation', from: 'kida', to: 'alienation', type: 'interprets', label: 'resistant subject', sourceIds: ['letts'], note: 'Alienation is central to Letts’s interpretation of Kid A and its unstable conceptual subject.' },
  { id: 'amnesiac-anti', from: 'amnesiac', to: 'anticapital', type: 'interprets', label: 'commodity critique', sourceIds: ['letts'], note: 'Letts connects the paired albums to anti-capitalist themes and Radiohead’s ambivalence toward success and commodity culture.' },
  { id: 'fitter-alien', from: 'fitter', to: 'alienation', type: 'interprets', label: 'technological subject', sourceIds: ['griffiths'], note: 'Placed as a thematic bridge from OK Computer’s technological language toward the later vanishing/alienated subject examined by Letts.' },

  { id: 'penderecki-okc', from: 'penderecki', to: 'okc', type: 'influenced-by', label: 'string-writing reference', sourceIds: ['guardian-2000'], note: 'Jonny Greenwood directly names Penderecki when describing influences on his string arrangements for OK Computer and Kid A.' },
  { id: 'messiaen-okc', from: 'messiaen', to: 'okc', type: 'influenced-by', label: 'compositional reference', sourceIds: ['guardian-2000'], note: 'Jonny Greenwood directly names Messiaen alongside Penderecki as an influence on his string work around OK Computer and Kid A.' },
  { id: 'autechre-kida', from: 'autechre', to: 'kida', type: 'influenced-by', label: 'electronic reference', sourceIds: ['guardian-2009', 'guardian-2000'], note: 'Autechre is named directly among Yorke’s electronic inspirations during the transition.' },
  { id: 'boards-kida', from: 'boards', to: 'kida', type: 'influenced-by', label: 'electronic reference', sourceIds: ['guardian-2009'], note: 'Boards of Canada is named directly in the band’s retrospective account of Yorke’s listening.' },
  { id: 'aphex-kida', from: 'aphex', to: 'kida', type: 'influenced-by', label: 'Warp listening', sourceIds: ['guardian-2000'], note: 'Contemporary interview material places Aphex Twin inside Yorke’s engagement with the Warp catalogue around Kid A.' },
]

export const kindLabels = {
  album: 'release',
  track: 'track',
  method: 'method',
  theme: 'theme',
  influence: 'influence',
} as const
